### ISSUE TITLE
the community version has too limited functions

### ISSUE THREAD

**Issue by itmisx** [testsigmahq/testsigma#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to add?

Surprised by the design of testsigma, but the community version has too limited functions, it can hardly be put into production, there is no team management, no project management, which is not conducive to community development

### Why should this be worked on?

with basic functions

**Comment by diveshmehta06** [comment]
Hi @itmisx The main focus of the community edition is the core automation capabilities, which are typical for everyone. Some of the features like test management and user management are not generic for everyone and are unique to the business based on their strategies and processes. 

Since Testsigma is an open-source project, teams can dig deep and add these features or integrate them with their existing systems as needed.
